
<div class="span1">
    
</div>
<div class="span10 page-back-all">
    <div class="container-fluid">
        <div class="span1 offset1"></div>
        <div class="span12">
            <div id="alert-login-faild"></div>
        </div>
        <div class="span1 offset1"></div>
    </div>
    <div class="container-fluid">
        <div class="span1">
            
        </div>
        <div class="span10 back-all-form">
            <div class="span12 back-all-title-form">Login Bands & Fans</div>
            <div class="span2">
                
            </div>
            <div class="span8">
                <div class="page-header">
                    <h5>Login with facebook account</h5>
                </div>
                <div  style="text-align: center"><a href="<?php echo APPLICATION_BASEURL; ?>/login"  id="fbloginlink" ><img src="https://s3-us-west-1.amazonaws.com/fivefourclubimages/frontend/fb-login.jpg"></a></div>
                <div class="page-header">
                    <h5>Login with account</h5>
                </div>
                <form id="form-sub" action="<?php echo APPLICATION_BASEURL; ?>/login">
                    <fieldset>
                        <div class="row-fluid">
                            <label>Email</label>
                            <input type="text" name="vEmail" placeholder="Email..." style="width:95%;" >
                            <label>Password</label>
                            <input type="password" name="vPassword" placeholder="Password..." style="width:95%;">
                        </div>
                        <div class="row-fluid">
                            <div class="span3">
                                <input type="button" value="Login" name="login-form" id="login-form" class="btn btn-success" />
                            </div>
                            <div class="span9">
                                <input type="checkbox" name="remmber" value="remmber">&nbsp;Remember Me?<br>
                            </div>
                        </div>
                        <div>
                            <a href="<?php echo APPLICATION_BASEURL; ?>/forget-password" >Forgot Password?</a>
                        </div>
                    </fieldset>
                </form>
            </div>
            <div class="span2"></div>
        </div>
        <div class="span1">
        </div>
    </div>
    
</div>



