
<div class="span1">
    
</div>
<div class="span10 page-back-all">
    <div class="container-fluid">
        <!--<div class="span1 offset1"></div>-->
        <div class="span12">
            <div id="alert-login-faild"></div>
        </div>
        <!--<div class="span1 offset1"></div>-->
    </div>
    <div class="container-fluid">
        <div class="span1">
            
        </div>
        <div class="span10 back-all-form">
            <div class="span12 back-all-title-form">Lost Password Recovery Form</div>
            <div class="page-header">
                <div class="container-fluid">
                 
                <p>If you have forgotten your password, you can request to have your emailed to you and to reset your password. When you fill in your registered email address, you will be sent instructions on how to reset your password.</p>
                </div>
            </div>
            
            <div class="span2">
                
            </div>
            <div class="span8">
<!--                <div class="page-header">
                    <h5>Get New Password</h5>
                </div>-->
                <form id="form-sub" action="<?php echo APPLICATION_BASEURL; ?>/forget-password">
                    <fieldset>
                        <div class="row-fluid">
                            <label>Email</label>
                            <input type="text" name="vEmail" placeholder="Email..." style="width:95%;" >
                        </div>
                        <div class="row-fluid">
                            <div class="span3">
                                <input type="button" value="Send Password" name="login-form" id="login-form" class="btn btn-success" />
                            </div>
                        </div>
                    </fieldset>
                </form>
            </div>
            <div class="span2"></div>
        </div>
        <div class="span1">
        </div>
    </div>
    
</div>
