
<div class="span1">
    
</div>
<div class="span10 page-back-all">
    <div class="container-fluid">
        <!--<div class="span1 offset1"></div>-->
        <div class="span12">
            <div id="alert-login-faild"></div>
        </div>
        <!--<div class="span1 offset1"></div>-->
    </div>
    <div class="container-fluid">
        <div class="span1">
            
        </div>
        <div class="span10 back-all-form">
            <div class="span12 back-all-title-form">The second part of the registration</div>
            <div class="span2">
                
            </div>
            <div class="span8">
                <form id="form-sub-signup-part2" action="<?php echo APPLICATION_BASEURL; ?>/signup">
                    <fieldset>
                        <div class="row-fluid">
                                                            <label>State of USA</label>
                                                            <select id="pre1_iState_id" name="iState_id" style="width:96%;">
                                                                <?php  foreach ($this->state as $key => $value) {
                                                                    print '<option value="'.$value['iId'].'">'.$value['vName'].'</option>';
                                                                  }                                                             
                                                                ?>
                                                            </select>
                                                            <!--<input type="text" id="pre1_iState_id" name="iState_id" placeholder="State..." style="width:93%;" >-->
                                                            <label>City</label>
                                                            <input type="text" id="pre1_vCity" name="vCity" placeholder="City..." style="width:93%;" >
                                                            <label>Market:</label>
                                                            <select id="pre1_iMarket_id" name="iMarket_id" style="width:96%;">
                                                                <?php  foreach ($this->market as $key => $value) {
                                                                    print '<option value="'.$value['iId'].'">'.$value['vTitle'].'</option>';
                                                                  }                                                             
                                                                ?>
                                                            </select>
                                                            
                                                            <label>Genres:</label>
                                                            <select id="pre1_vGenre_ids" name="vGenre_ids" class="select2" multiple="multiple" style="width:96%; height: 160px;margin-bottom: 5px">
                                                                  <?php  foreach ($this->genres as $key => $value) {
                                                                      fb($value);
                                                                        print '<option value="'.$value['iId'].'">'.$value['vTitle'].'</option>';
                                                                      }                                                             
                                                                    ?>
                                                            </select>
                        </div>
                        <div class="row-fluid">
                            <div class="span3">
                                <input type="button" value="Register" name="signup-part2-form" id="signup-part2-form" class="btn btn-primary" style="margin-top: 5px"/>
                            </div>
                        </div>
                    </fieldset>
                </form>
            </div>
            <div class="span2"></div>
        </div>
        <div class="span1">
        </div>
    </div>
    
</div>
