<!--
<div class="span1">
    
</div>
<div class="span10 page-back-all">
    <div class="container-fluid">
        <div class="span1 offset1"></div>
        <div class="span12">
            <div id="alert-login-faild"></div>
        </div>
        <div class="span1 offset1"></div>
    </div>
    <div class="container-fluid">
        <div class="span1"></div>
        <div class="span10 back-all-form">
            <div class="span12 back-all-title-form">The second part of the registration</div>
            <div class="span2"></div>
            <div class="span8">
                <form id="form-sub-signup-part2" action="<?php echo APPLICATION_BASEURL; ?>/signup">
                    <fieldset>
                        <div class="row-fluid">
                            <label>State of USA</label>
                            <select id="pre1_iState_id" name="iState_id" style="width:96%;">
                                <?php  foreach ($this->state as $key => $value) {
                                    print '<option value="'.$value['iId'].'">'.$value['vName'].'</option>';
                                  }                                                             
                                ?>
                            </select>
                            <label>City</label>
                            <input type="text" id="pre1_vCity" name="vCity" placeholder="City..." style="width:93%;" >
                            <label>Market:</label>
                            <select id="pre1_iMarket_id" name="iMarket_id" style="width:96%;">
                                <?php  foreach ($this->market as $key => $value) {
                                    print '<option value="'.$value['iId'].'">'.$value['vTitle'].'</option>';
                                  }                                                             
                                ?>
                            </select>
                            <label>Genres:</label>
                            <select id="pre1_vGenre_ids" name="vGenre_ids" class="select2" multiple="multiple" style="width:96%; height: 160px;margin-bottom: 5px">
                                  <?php  foreach ($this->genres as $key => $value) {
                                        print '<option value="'.$value['iId'].'">'.$value['vTitle'].'</option>';
                                      }                                                             
                                    ?>
                            </select>
                        </div>
                        <div class="row-fluid">
                            <div class="span3">
                                <input type="button" value="Register" name="signup-part2-form" id="signup-part2-form" class="btn btn-primary" style="margin-top: 5px" />
                            </div>
                        </div>
                    </fieldset>
                </form>
            </div>
            <div class="span2"></div>
        </div>
        <div class="span1"></div>
    </div>
    
</div>-->




<html>
    <head>
        <link href='http://fonts.googleapis.com/css?family=Open+Sans:300,400' rel='stylesheet' type='text/css'>
        <link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro' rel='stylesheet' type='text/css'>
    </head>
    
    <body>
        <div class="darkyellow-login" style="background:#f59711; width:100%; height:150px; margin:0 auto; padding:0;">
            <div class="container-fluid">
                <div class="span1 offset1"></div>
                <div class="span12">
                    <div id="alert-login-faild"></div>
                </div>
                <div class="span1 offset1"></div>
            </div>
            <p class="loginfbt">Login Bands &amp; Fans</p>
            <p class="loginfb">Use Facebook, Twitter or your email to <font color="#000000">Login.</font></p>
        </div>
        
        
        
        <div id="signupContent" style="height:350px;">
            <div class="container">
                <div class="row">
                    <div class="span12">
                        <div class="specialSignUp">
                            <div class="row">
                                <div class="span12">
<!--                                    <div class="span1">-->
                                        <div class="loginform" style="width:500px; float:left; height:200px; padding-left: 280px; padding-top:20px;">
                                            <form id="form-sub-signup-part2" action="<?php echo APPLICATION_BASEURL; ?>/signup" autocomplete="off">
                                                <p class="username">State of USA</p>
                                                <select class="loginform" id="pre1_iState_id" name="iState_id" style="width:96%;">
                                                    <?php  foreach ($this->state as $key => $value) {
                                                        print '<option value="'.$value['iId'].'">'.$value['vName'].'</option>';
                                                    }                                                             
                                                    ?>
                                                </select>
                                                
                                                <p class="username">City:</p>
                                                <input class="loginform" type="text" id="pre1_vCity" name="vCity" placeholder="City..." style="width:93%;" >
                                                
                                                <p class="username">Market:</p>
                                                <select class="loginform" id="pre1_iMarket_id" name="iMarket_id" style="width:96%;">
                                                    <?php  foreach ($this->market as $key => $value) {
                                                        print '<option value="'.$value['iId'].'">'.$value['vTitle'].'</option>';
                                                    }                                                             
                                                    ?>
                                                </select>
                                                
                                                <p class="username">Genres:</p>
                                                <select id="pre1_vGenre_ids" name="vGenre_ids" class="select2 loginform" multiple="multiple" style="width:96%; height: 160px;margin-bottom: 5px">
                                                    <?php  foreach ($this->genres as $key => $value) {
                                                            print '<option value="'.$value['iId'].'">'.$value['vTitle'].'</option>';
                                                        }                                                             
                                                        ?>
                                                </select>
                                                <div class="span3 signupBtns" style="margin:0;">
                                                    <input type="button" value="Register" name="signup-part2-form" id="signup-part2-form" class="btn btn-inverse pull-left" style="margin-top: 5px" />
                                                </div>
                                                
                                            </form>
                                        </div>
<!--                                    </div>-->
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>
