<div class="span1"></div>
<div class="span10 page-back-all">
    <div class="container-fluid">
        <div class="span12">
                <?php
                    if($this->view->form){
                        fb($this->view->form->getMessages());
                    }
                    if ( $this->errorMessage ) {
                ?>
                    <div class="alert alert-error">
                        <?php print $this->errorMessage; ?>
                    </div>
                <?php }if ( $this->SuccessMessage ) { ?>
                    <script>
                        $("#alert-signup").remove();
                    </script>
                    <div class="alert alert-success">
                        <?php print $this->SuccessMessage; ?>
                        <script>
                            var $projectExecPath = '<?php echo APPLICATION_BASEURL.'/wellcome'; ?>';
                            var delay = 2000; //Your delay in milliseconds
                            setTimeout(function(){ window.location = $projectExecPath; }, delay);
                        </script>
                    </div>
                 <?php
                }
                ?>
            <div  id="alert-signup" ></div>
        </div>
    </div>
    <div class="container-fluid">
        <div class="span1">
            
        </div>
        <div class="span10 back-all-form">
            <div class="span12 back-all-title-form">Register Bands Form</div>
            <div class="span2">
                
            </div>
            <div class="span8">
                
                <div class="page-header">
                    <h5>Create your account with facebook account</h5>
                </div>
                    <div  style="text-align: center"><a href="<?php echo APPLICATION_BASEURL; ?>/signup"  id="fbloginlink" ><img src="https://s3-us-west-1.amazonaws.com/fivefourclubimages/frontend/fb-login.jpg"></a></div>
                <div  class="page-header">
                    <h5>Create your account</h5>
                </div>
                <?php print $this->form; ?>
            </div>
            <div class="span2"></div>
        </div>
        <div class="span1"></div>
    </div>
</div>


