

<div class="span3">
   
    
</div>
<div class="span3">
    <!--<div class="container-fluid">-->
        <ul class="nav">
                          <li><a href="<?php echo APPLICATION_BASEURL ?>/signup/fans"><button class="btn btn-large btn-block btn-primary " type="button">SignUp Fans</button></a></li>
                        
                      </ul>
                        
    <!--</div>-->
</div>
<div class="span3">
    <!--<div class="container-fluid">-->
                        <ul class="nav">
                          <li><a href="<?php echo APPLICATION_BASEURL ?>/signup/bands"><button class="btn btn-large  btn-block btn-primary" type="button">SignUp bands</button></a></li>
                      </ul>
    <!--</div>-->
</div>
<div class="span3">
    
    
</div>

<!--<form enctype="application/x-www-form-urlencoded" method="post" action=""><dl class="zend_form">
<dt id="vEmail-label"><label for="vEmail" class="required">Email</label></dt>
<dd id="vEmail-element">
<input type="text" name="vEmail" id="vEmail" value="" required="required"></dd>
<dt id="vPassword-label"><label for="vPassword" class="required">پسورد</label></dt>
<dd id="vPassword-element">
<input type="password" name="vPassword" id="vPassword" value="" required="required"></dd>
<dt id="vPasswordConfirm-label"><label for="vPasswordConfirm" class="required">confirm Password</label></dt>
<dd id="vPasswordConfirm-element">
<input type="password" name="vPasswordConfirm" id="vPasswordConfirm" value="" required="required"></dd>
<dt id="vMessage-label"><label for="vMessage" class="optional">tozihat</label></dt>
<dd id="vMessage-element">
<textarea name="vMessage" id="vMessage" COLS="15" ROWS="5" rows="24" cols="80"></textarea></dd>
<dt id="save_changes-label">&#160;</dt><dd id="save_changes-element">
<input type="submit" name="save_changes" id="save_changes" value="save info"></dd></dl></form>-->


<!--    <form method="post" action="">
        <div class="row-fluid">
            <div class="span6">
                <dt>
                <label for="majid">First Name</label>
                </dt>
                <dd>
                <input type="text" id="majid" name="majid" placeholder="First Name..."></dd>
                <dt>
                <label for="azad">Last Name</label>
                </dt>
                <dd>
                <input type="text" id="azad" name="azad" placeholder="Last Name...">
                </dd>
                <dt>
                <label for="email">Email</label>
                </dt>
                <dd>
                <input type="text" id="email" name="email" placeholder="Email..." required="required">
                </dd>
                
                
       
                <dt>
                <label for="vPassword">Password</label>
                </dt>
                <dd>
                <input type="password" id="vPassword" name="vPassword" placeholder="Pssword..." required="required">
                </dd>
                <dt>
                <label for="vPasswordConfirm">Password Confirm</label>
                </dt>
                <dd>
                <input type="password" id="vPasswordConfirm" name="vPasswordConfirm" placeholder="Password Confirm..." required="required">
                </dd></br>
                <dt>
                    
                </dt>
                <dd>
                    <button type="submit" class="btn" name="save_changes" id="save_changes">Submit</button>
                </dd>
                
            </div>
            
           
        </div>
           
    </form>-->
