<div class="span12" id="alert-login-faild"></div>
<div class="row-fluid span12" id="form-edit-band-id" style="margin:0;display: none">
    <ul class="nav nav-tabs" id="edit-information-tab-id" style="margin: 0">
    <li class="active"><a href="#basicInfo">Basic Info</a></li>
    <li><a href="#othreInfo">Other Info</a></li>
    <li><a href="#changePassword">Change Password</a></li>
</ul>
 
<div class="tab-content">
    <div class="tab-pane active" id="basicInfo">
        <div class="well" style="margin:0;">
            <div class="videoform" style=" height:auto; min-height:300px; margin:0 auto; padding:0; width:1070px;">
                <form id="form-band-edit-id" action="<?php echo APPLICATION_BASEURL; ?>/profile" style="margin:0;"  >
                    <div class="leftform">
                        <label>Title</label>
                        <input type="text" id="pre_vTitle" name="vTitle" placeholder="Title..." style="width:93%;" >
                        <label>City</label>
                        <input type="text" id="pre_vCity" name="vCity" placeholder="City..." style="width:93%;" >
                        <label>State</label>
                        <select id="pre_iState_id" name="iState_id" style="width:96%;">
                            <?php  
                                foreach ($this->arrayFinalView['formInfo']['stateList'] as $key => $value) {
                                    print '<option value="'.$value['iId'].'">'.$value['vName'].'</option>';
                                } 
                            ?>
                        </select>
                        <input class="submitvideo" value="Close" id="more-info-form-close" style="text-align: center;cursor: pointer;width: 450px !important"/>
                    </div>
                    <div class="rightform">
                        <label>Email</label>
                        <input type="text" id="pre_vEmail" name="vEmail" placeholder="Email..." style="width:93%;" >
                        <label>Market:</label>
                        <select id="pre_iMarket_id" name="iMarket_id" style="width:96%;">
                            <?php  
                                foreach ($this->arrayFinalView['formInfo']['marketList'] as $key => $value) {
                                    print '<option value="'.$value['iId'].'">'.$value['vTitle'].'</option>';
                                }                                                             
                            ?>
                        </select>
                        <label>Genres:</label>

                            <select id="pre_vGenre_ids" name="vGenre_ids" class="select2" multiple="multiple" style="width:96%; height: 160px">
                                <?php  
                                    foreach ($this->arrayFinalView['formInfo']['genresList'] as $key => $value) {
                                        print '<option value="'.$value['iId'].'">'.$value['vTitle'].'</option>';
                                    }                                                             
                                ?>
                            </select>
                        <input class="submitvideo" value="Save Information" id="more-info-form-save" style="text-align: center;cursor: pointer;width: 550px !important;margin-top: 40px"/>
                    </div>
                </form>
            </div>
        </div>  <!--end of videoform-->
    </div>
    <div class="tab-pane" id="othreInfo">
        <div class="well" style="margin:0;">
                <div class="videoform" style=" height:auto; min-height:330px; margin:0 auto; padding:0; width:1070px;">
                    <form id="form-band-edit-id-tab2" action="<?php echo APPLICATION_BASEURL; ?>/profile" style="margin:0;"  >
                        <div class="leftform">
                            <label>website</label>
                            <input type="text" id="pre_vWebsite" data-tab2="data" name="vWebsite" placeholder="Website..." style="width:93%;" >
                            <label>Facebook</label>
                            <input type="text" id="pre_vFacebook" data-tab2="data" name="vFacebook" placeholder="Facebook..." style="width:93%;" >
                            <label>Twitter</label>
                            <input type="text" id="pre_vTwitter" data-tab2="data" name="vTwitter" placeholder="Twitter..." style="width:93%;" >

                            <input class="submitvideo" value="Close" id="more-info-form-close-tab2" style="text-align: center;cursor: pointer;width: 450px !important"/>
                        </div>
                        <div class="rightform">
                            <label>Instagram</label>
                            <input type="text" id="pre_vInstagram" data-tab2="data" name="vInstagram" placeholder="Instagram..." style="width:93%;" >
                            <label>Spotify</label>
                            <input type="text" id="pre_vSpotify" data-tab2="data" name="vSpotify" placeholder="Spotify..." style="width:93%;" >
                            <label>Soundcloud</label>
                            <input type="text" id="pre_vSoundcloud" data-tab2="data" name="vSoundcloud" placeholder="Soundcloud..." style="width:93%;" >
                            <input class="submitvideo" value="Save Information" id="more-info-form-save-tab2" style="text-align: center;cursor: pointer;width: 550px !important"/>
                        </div>
                    </form>
                </div>
            </div>  <!--end of videoform-->
 
    </div>
    <div class="tab-pane" id="changePassword">
        <div class="well" style="margin:0;">
                <div class="videoform" style=" height:auto; min-height:300px; margin:0 auto; padding:0; width:1070px;">
                    <form id="form-band-edit-id-tab3" action="<?php echo APPLICATION_BASEURL; ?>/profile" style="margin:0;"  >
                        <div class="leftform">
                            <label>Current Password</label>
                            <input type="password" data-tab="password" name="CuPassword" placeholder="Current Password..." style="width:95%;" >
                            <label>New Password</label>
                            <input type="password" data-tab="password" name="vPassword" placeholder="New Password..." style="width:95%;" >
                            <label>Password Confirm</label>
                            <input type="password" data-tab="password" name="vPasswordConfirm" placeholder="Password Confirm..." style="width:95%;">
                            
                        </div>
                        <div class="rightform">
                            <input class="submitvideo" value="Save Information" id="more-info-form-save-tab3" style="text-align: center;cursor: pointer;width: 450px !important;margin-top: 175px;margin-bottom: 10px"/>
                            <input class="submitvideo" value="Close" id="more-info-form-close-tab3" style="text-align: center;cursor: pointer;width: 450px !important"/>
                            
                        </div>
                    </form>
                </div>
            </div>  <!--end of videoform-->
 
    </div>
</div>
    
</div>

<div class="row">
    <div class="span5">
            <div class="hide" id="hidden_block_vote_id">
                <div class="alert alert-block" id="alert_block_vote_id">
                    <h4>Warning!</h4>
                    Best check yo self, you're not...
                </div>
            </div>
            <div class="hide" id="hidden_success_vote_id">
                <div class="alert alert-success" id="alert_success_vote_id">
                    <h4>success!</h4>
                    Best check yo self, you're not...
                </div>
            </div>
        </div>
</div>
<div data-login="<?php print $this->login ?>" data-idProfile="" id="<?php print $this->idProfile ?>"></div>
<div id="bandContent">
<div class="container">
  <div class="row">
	  <div class="span4">
              <div class="pull-left"><h2><?php print $this->arrayFinalView['bandName']; ?></h2></div><div class="pull-left" style="margin: 10px"><?php if($this->arrayFinalView['aloweEditProfile'] == 'Yes'){ ?><div class="btn btn-small btn-primary" id="band-edit-btn-id">Edit</div><?php } ?></div>
		<img src="<?php echo APPLICATION_BASEURL; ?>/public/uploaded_resource/frontend/member/profile-image/<?php print $this->arrayFinalView['picProfile']; ?>" alt="TEMP-band-video" width="356" height="299" />
	  </div>
	  <div class="span8" style="width:529px; margin:54px 0 0 48px;">
		<h2>
                    <button style="width: 529px; background-color: #ffbb34;" id="btn_add_vote_id" data-trigger="hover"  class="btn btn-primary" value="addVote">VOTE!</button>
                    <button style="width: 529px; background-color: #ffbb34" id="btn_add_vote_notlogin_id" class="btn btn-primary hide">VOTE!</button>
                </h2>

		<table class="playTable">
                    <?php if(!empty($this->arrayFinalView['tracks'])){ foreach ($this->arrayFinalView['tracks'] as $key => $value) { ?>
                        <tr>
                            <td>
                                <p class="titlep"><?php print $value['vTitle']  ?></p>
                            </td>
                            <td>
                                <img src="<?php print APPLICATION_BASEURL .'/public/skins/frontend/default/images/img/fb_tweet.png' ?>" alt="fbt" />
                            </td>
                            <td>
                                <i class="icon-music icon-white"></i><div id="<?php print 'iClick_'.$value['iId']; ?>"> <?php print $value['iClick'] ?></div>
                            </td>
                            <td>
                                <img data-play="" id="playeBtn_<?php print $value['iId']; ?>" <?php print 'playe_buttom_'.$value['iId']; ?> src="<?php print APPLICATION_BASEURL .'/public/skins/frontend/default/images/img/white_arrow.png' ?>" alt="play"  onclick="play_audio(<?php print $value['iId']; ?>)"/>
                                
                                <?php // fb(); ?>
                                
                                
                                <audio id="<?php print 'player_'.$value['iId']; ?>">
                                    <source src="<?php print APPLICATION_BASEURL .'/public/uploaded_resource/frontend/band-'.$value['iBand_id'].'/audio/'.$value['vFile_mp3']; ?>" />
                                    <?php if($value['vFile_ogg']!=''){ ?>
                                        <source src="<?php print APPLICATION_BASEURL .'/public/uploaded_resource/frontend/band-'.$value['iBand_id'].'/audio/'.$value['vFile_ogg']; ?>" />
                                    <?php } ?>
                                </audio>
                            </td>
                            
                        </tr>
                        <tr style="height:2px;"></tr>
                    <?php }} ?>
				
			</tr>
		</table>
	  </div><!--/.span5 -->
  </div><!-- /.row -->
</div><!-- /.container -->
</div>


<div id="votingContent" style="background:#333;">
	<div class="container">
		<div class="row">
                    <div class="span12">
                            <h2 class="headline" style="text-align:center; font-size:30px; margin-top:5px;"><?php print $this->arrayFinalView['bandName']; ?> From <?php echo $this->arrayFinalView['location'] ?></h2>
                    </div>
		</div><!-- /.row -->
		
		<div class="row-fluid">
			
                    <div class="span6" style="float:left; margin-top:15px;">
			  
                        <div class="tab-body1" style="float:right;">
                            <!--<p>23932</p>-->
                            <p><?php if($this->arrayFinalView['overallVotes']){echo $this->arrayFinalView['overallVotes']; }else{echo '0';} ?></p>
                            <p><?php if($this->arrayFinalView['fanOfBand']){echo $this->arrayFinalView['fanOfBand']; }else{echo '0';} ?></p>
                            <p><?php if($this->arrayFinalView['track']){echo $this->arrayFinalView['track']; }else{echo '0';} ?></p>
                        </div>
                        <div class="tab-body" style="float:right;">
                            <!--<p>Votes this Round:</p>-->
                            <p>Overall Votes:</p>
                            <p>Fan:</p>
                            <p>Total Plays:</p>
                        </div>
                    </div>
                    <div class="vrow"></div>
			
            
                    <div class="span5" style="float:left; margin-top:15px;">
                        <div class="tab-body" style="float:left;">
                            <p>Location:</p>
                            <p>Market:</p>
                            <p>Genre:</p>
                            <p>Members:</p>
                        </div>
                        <div class="tab-body1" style="float:left; width:160px;">
                            <p><?php if($this->arrayFinalView['location']){echo $this->arrayFinalView['location']; }else{echo '-'; } ?></p>
                            <p><?php if($this->arrayFinalView['market']){echo $this->arrayFinalView['market']; }else{echo '-'; } ?></p>
                            <p><?php if($this->arrayFinalView['genres']){echo $this->arrayFinalView['genres']; }else{echo '-';} ?></p>
                            <p><?php if($this->arrayFinalView['members']){echo $this->arrayFinalView['members'];}else{echo '0';} ?></p>
                        </div>
                    </div>
			
		</div><!-- /.row -->

                <div style="margin:10px auto; width:506px;">
                    
                    <?php if( $this->arrayFinalView['bandDetails']['vWebsite'] ) { ?>
                        <a href="<?php print $this->arrayFinalView['bandDetails']['vWebsite']; ?>"><img src="<?php print APPLICATION_BASEURL .'/public/skins/frontend/default/images/img/link_icon.png'?>" alt="<?php print $this->arrayFinalView['bandDetails']['vWebsite']; ?>" /></a>
                    <?php } ?>

                    <?php if( $this->arrayFinalView['bandDetails']['vFacebook'] ) { ?>
                        <a href="https://www.facebook.com/<?php print $this->arrayFinalView['bandDetails']['vFacebook']; ?>"><img src="<?php print APPLICATION_BASEURL .'/public/skins/frontend/default/images/img/fb_icon.png'?>" alt="<?php print $this->arrayFinalView['bandDetails']['vFacebook']; ?>" /></a>
                    <?php } ?>

                    <?php if( $this->arrayFinalView['bandDetails']['vTwitter'] ) { ?>
                        <a href="http://twitter.com/<?php print $this->arrayFinalView['bandDetails']['vTwitter']; ?>"><img src="<?php print APPLICATION_BASEURL .'/public/skins/frontend/default/images/img/tweet_icon.png'?>" alt="<?php print $this->arrayFinalView['bandDetails']['vTwitter']; ?>" /></a>
                    <?php } ?>

                    <?php if( $this->arrayFinalView['bandDetails']['vInstagram'] ) { ?>
                        <a href="http://instagram.com/<?php print $this->arrayFinalView['bandDetails']['vInstagram']; ?>"><img src="<?php print APPLICATION_BASEURL .'/public/skins/frontend/default/images/img/photo_icon.png'?>" alt="<?php print $this->arrayFinalView['bandDetails']['vInstagram']; ?>" /></a>
                    <?php } ?>

                    <?php if( $this->arrayFinalView['bandDetails']['vSpotify'] ) { ?>
                        <a href="http://open.spotify.com/artist/<?php print $this->arrayFinalView['bandDetails']['vSpotify']; ?>"> <img src="<?php print APPLICATION_BASEURL .'/public/skins/frontend/default/images/img/read_icon.png'?>" alt="<?php print $this->arrayFinalView['bandDetails']['vSpotify']; ?>" /></a>
                    <?php } ?>

                    <?php if( $this->arrayFinalView['bandDetails']['vSoundcloud'] ) { ?>
                        <a href="https://soundcloud.com/<?php print $this->arrayFinalView['bandDetails']['vSoundcloud']; ?>"><img src="<?php print APPLICATION_BASEURL .'/public/skins/frontend/default/images/img/cloud_icon.png'?>" alt="<?php print $this->arrayFinalView['bandDetails']['vSoundcloud']; ?>" style="margin-top:10px;" /></a>
                    <?php } ?>

                </div>
		
	</div><!-- /.row -->

  </div><!-- /.container -->
</div><!-- /#votingContent -->

<?php if(!empty($this->arrayFinalView['eightVideo'][0])){ ?>

<!-- Modal -->
<div id="movie-show" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
<!--        <img id="movie-image-modal-id" src="" style="width: 50px;float: left;margin-right: 5px"/>-->
        <h3 id="movie-title-modal-id"></h3>
        </div>
        <div class="modal-body">
            <div id="movie-embed-modal-id"></div>
        </div>
</div>
<div id="votingContent">
	<div class="container">
		<div class="row">
			<div class="span12" style="margin:0 0 0 40px;">
				<h2 class="headline" style="text-align:center; font-size:35px; margin-top:20px;"><?php print $this->arrayFinalView['bandName']; ?> Videos</h2>
			</div>
		</div><!-- /.row -->
		
		<div class="row-fluid">
			
			<div class="span6" style="width:100%; margin:0 auto;">
                            
                            <?php if($this->arrayFinalView['eightVideo'][0][0] != NULL){ ?>
                            <span class="bandProfile1" style="float:left; margin:0 5px 0 55px;width:250px;" onclick="show_movie(<?php print $this->arrayFinalView['eightVideo'][0][0]['iId']; ?>)">
                                    <img src="<?php print $this->arrayFinalView['eightVideo'][0][0]['tVideo_image']; ?>" alt="video" class="imgvid" style="margin:0;"/>
                                    <p><?php print $this->arrayFinalView['eightVideo'][0][0]['vVideo_title']; ?></p>
                                </span>
                            <?php }if($this->arrayFinalView['eightVideo'][0][1] != NULL){ ?>
                                <span class="bandProfile1" style="float:left;margin:0 5px 0 5px;width:250px;" onclick="show_movie(<?php print $this->arrayFinalView['eightVideo'][0][1]['iId']; ?>)">
                                    <img src="<?php print $this->arrayFinalView['eightVideo'][0][1]['tVideo_image']; ?>" alt="video" class="imgvid" style="margin:0;" />
                                    <p><?php print $this->arrayFinalView['eightVideo'][0][1]['vVideo_title']; ?></p>
                                </span>
                            <?php }if($this->arrayFinalView['eightVideo'][0][2] != NULL){ ?>
                                <span class="bandProfile1" style="float:left;margin:0 5px 0 5px;width:250px;" onclick="show_movie(<?php print $this->arrayFinalView['eightVideo'][0][2]['iId']; ?>)">
                                    <img src="<?php print $this->arrayFinalView['eightVideo'][0][2]['tVideo_image']; ?>" alt="video" class="imgvid"  style="margin:0;"/>
                                    <p><?php print $this->arrayFinalView['eightVideo'][0][2]['vVideo_title']; ?></p>
                                </span>
                            <?php }if($this->arrayFinalView['eightVideo'][0][3] != NULL){ ?>
                                <span class="bandProfile1" style="float:left;margin:0 5px 0 5px;width:250px;" onclick="show_movie(<?php print $this->arrayFinalView['eightVideo'][0][3]['iId']; ?>)">
                                    <img src="<?php print $this->arrayFinalView['eightVideo'][0][3]['tVideo_image']; ?>" alt="video" class="imgvid" style="margin:0;" />
                                    <p><?php print $this->arrayFinalView['eightVideo'][0][3]['vVideo_title']; ?></p>
                                </span>
                            <?php } ?>
			</div>



			<div class="span6" style="width:100%; margin:0 auto;">
                            <?php if($this->arrayFinalView['eightVideo'][0][4] != NULL){ ?>
                                <span class="bandProfile1" style="float:left; margin:0 5px 0 55px;width:250px;" onclick="show_movie(<?php print $this->arrayFinalView['eightVideo'][0][4]['iId']; ?>)">
                                    <img src="<?php print $this->arrayFinalView['eightVideo'][0][4]['tVideo_image']; ?>" alt="video" class="imgvid" style="margin:0;"/>
                                    <p><?php print $this->arrayFinalView['eightVideo'][0][4]['vVideo_title']; ?></p>
                                </span>
                            <?php }if($this->arrayFinalView['eightVideo'][0][5] != NULL){ ?>
                                <span class="bandProfile1" style="float:left;margin:0 5px 0 5px;width:250px;" onclick="show_movie(<?php print $this->arrayFinalView['eightVideo'][0][5]['iId']; ?>)">
                                    <img src="<?php print $this->arrayFinalView['eightVideo'][0][5]['tVideo_image']; ?>" alt="video" class="imgvid" style="margin:0;" />
                                    <p><?php print $this->arrayFinalView['eightVideo'][0][5]['vVideo_title']; ?></p>
                                </span>
                            <?php }if($this->arrayFinalView['eightVideo'][0][6] != NULL){ ?>
                                <span class="bandProfile1" style="float:left;margin:0 5px 0 5px;width:250px;" onclick="show_movie(<?php print $this->arrayFinalView['eightVideo'][0][7]['iId']; ?>)">
                                    <img src="<?php print $this->arrayFinalView['eightVideo'][0][6]['tVideo_image']; ?>" alt="video" class="imgvid"  style="margin:0;"/>
                                    <p><?php print $this->arrayFinalView['eightVideo'][0][6]['vVideo_title']; ?></p>
                                </span>
                            <?php }if($this->arrayFinalView['eightVideo'][0][7] != NULL){ ?>
                                <span class="bandProfile1" style="float:left;margin:0 5px 0 5px;width:250px;" onclick="show_movie(<?php print $this->arrayFinalView['eightVideo'][0][8]['iId']; ?>)">
                                    <img src="<?php print $this->arrayFinalView['eightVideo'][0][7]['tVideo_image']; ?>" alt="video" class="imgvid" style="margin:0;" />
                                    <p><?php print $this->arrayFinalView['eightVideo'][0][7]['vVideo_title']; ?></p>
                                </span>
                            <?php } ?>
			</div>
			
		</div><!-- /.row -->
		<?php if($this->arrayFinalView['eightVideo'][1] > 8){ ?>
                <div class="viewall"><a href="<?php echo APPLICATION_BASEURL.'/movies/index/id/'.$this->arrayFinalView['member_id']; ?>" class="">VIEW ALL VIDEOS</a></div>
                <?php } ?>
	</div><!-- /.row -->
  </div><!-- /.container -->
  <?php  } ?>
</div><!-- /#votingContent -->


<?php if(!empty($this->arrayFinalView['eightPhoto'][0])){ ?>
<div id="votingContent" style="background:#171c23;">
	<div class="container">
		<div class="row">
			<div class="span12">
				<h2 class="headline" style="text-align:center; font-size:30px; margin-top:20px;"><?php print $this->arrayFinalView['bandName']; ?> Photos</h2>
			</div>
		</div><!-- /.row -->
		
		<div class="row-fluid">
                    
                    <div class="span6" style="width:100%; margin:0 auto;">
                        <?php  if($this->arrayFinalView['eightPhoto'][0][0] != NULL){ ?>
                            <span class="bandProfile1" style="float:left; margin:0 5px 15px 55px;width:201px;">
                                <a data-height="<?php echo $this->arrayFinalView['eightPhoto'][0][0]['height']; ?>" data-width="<?php echo $this->arrayFinalView['eightPhoto'][0][0]['width']; ?>" href="<?php print APPLICATION_BASEURL .'/public/uploaded_resource/frontend/member/profile-image/'.$this->arrayFinalView['eightPhoto'][0][0]['vImg'] ?>" data-dateCreate="<?php echo $this->arrayFinalView['eightPhoto'][0][0]['dDate_create']; ?>" data-desc="<?php echo $this->arrayFinalView['eightPhoto'][0][0]['tDesc']; ?>" data-img="<?php echo $this->arrayFinalView['eightPhoto'][0][0]['vImg']; ?>">
                                    <img width="201px" height="165px" src="<?php print APPLICATION_BASEURL .'/public/uploaded_resource/frontend/member/profile-image/'.$this->arrayFinalView['eightPhoto'][0][0]['vImg'] ?>" alt="video" class="imgvid" style="margin:0;"/>
                                </a>
                            </span>
                        <?php }if($this->arrayFinalView['eightPhoto'][0][1] != NULL){ ?>
                            <span class="bandProfile1" style="float:left;margin:0 5px 15px 5px;width:201px;">
                                <a data-height="<?php echo $this->arrayFinalView['eightPhoto'][0][1]['height']; ?>" data-width="<?php echo $this->arrayFinalView['eightPhoto'][0][1]['width']; ?>" href="<?php print APPLICATION_BASEURL .'/public/uploaded_resource/frontend/member/profile-image/'.$this->arrayFinalView['eightPhoto'][0][1]['vImg'] ?>" data-dateCreate="<?php echo $this->arrayFinalView['eightPhoto'][0][1]['dDate_create']; ?>" data-desc="<?php echo $this->arrayFinalView['eightPhoto'][0][1]['tDesc']; ?>" data-img="<?php echo $this->arrayFinalView['eightPhoto'][0][1]['vImg']; ?>">
                                    <img width="201px" height="165px" src="<?php print APPLICATION_BASEURL .'/public/uploaded_resource/frontend/member/profile-image/'.$this->arrayFinalView['eightPhoto'][0][1]['vImg'] ?>" alt="video" class="imgvid" style="margin:0;" />
                                </a>
                            </span>
                        <?php }if($this->arrayFinalView['eightPhoto'][0][2] != NULL){ ?>
                            <span class="bandProfile1" style="float:left;margin:0 5px 15px 5px;width:201px;">
                                <a data-height="<?php echo $this->arrayFinalView['eightPhoto'][0][2]['height']; ?>" data-width="<?php echo $this->arrayFinalView['eightPhoto'][0][2]['width']; ?>" href="<?php print APPLICATION_BASEURL .'/public/uploaded_resource/frontend/member/profile-image/'.$this->arrayFinalView['eightPhoto'][0][2]['vImg'] ?>" data-dateCreate="<?php echo $this->arrayFinalView['eightPhoto'][0][2]['dDate_create']; ?>" data-desc="<?php echo $this->arrayFinalView['eightPhoto'][0][2]['tDesc']; ?>" data-img="<?php echo $this->arrayFinalView['eightPhoto'][0][2]['vImg']; ?>">
                                    <img width="201px" height="165px" src="<?php print APPLICATION_BASEURL .'/public/uploaded_resource/frontend/member/profile-image/'.$this->arrayFinalView['eightPhoto'][0][2]['vImg'] ?>" alt="video" class="imgvid"  style="margin:0;"/>
                                </a>
                            </span>
                        <?php }if($this->arrayFinalView['eightPhoto'][0][3] != NULL){ ?>
                            <span class="bandProfile1" style="float:left;margin:0 5px 15px 5px;width:201px;">
                                <a data-height="<?php echo $this->arrayFinalView['eightPhoto'][0][3]['height']; ?>" data-width="<?php echo $this->arrayFinalView['eightPhoto'][0][3]['width']; ?>" href="<?php print APPLICATION_BASEURL .'/public/uploaded_resource/frontend/member/profile-image/'.$this->arrayFinalView['eightPhoto'][0][3]['vImg'] ?>" data-dateCreate="<?php echo $this->arrayFinalView['eightPhoto'][0][3]['dDate_create']; ?>" data-desc="<?php echo $this->arrayFinalView['eightPhoto'][0][3]['tDesc']; ?>" data-img="<?php echo $this->arrayFinalView['eightPhoto'][0][3]['vImg']; ?>">
                                    <img width="201px" height="165px" src="<?php print APPLICATION_BASEURL .'/public/uploaded_resource/frontend/member/profile-image/'.$this->arrayFinalView['eightPhoto'][0][3]['vImg'] ?>" alt="video" class="imgvid" style="margin:0;" />
                                </a>
                            </span>
                        <?php }if($this->arrayFinalView['eightPhoto'][0][4] != NULL){ ?>
                            <span class="bandProfile1" style="float:left;margin:0 5px 15px 5px;width:201px;">
                                <a data-height="<?php echo $this->arrayFinalView['eightPhoto'][0][4]['height']; ?>" data-width="<?php echo $this->arrayFinalView['eightPhoto'][0][4]['width']; ?>" href="<?php print APPLICATION_BASEURL .'/public/uploaded_resource/frontend/member/profile-image/'.$this->arrayFinalView['eightPhoto'][0][4]['vImg'] ?>" data-dateCreate="<?php echo $this->arrayFinalView['eightPhoto'][0][4]['dDate_create']; ?>" data-desc="<?php echo $this->arrayFinalView['eightPhoto'][0][4]['tDesc']; ?>" data-img="<?php echo $this->arrayFinalView['eightPhoto'][0][4]['vImg']; ?>">
                                    <img width="201px" height="165px" src="<?php print APPLICATION_BASEURL .'/public/uploaded_resource/frontend/member/profile-image/'.$this->arrayFinalView['eightPhoto'][0][4]['vImg'] ?>" alt="video" class="imgvid" style="margin:0;" />
                                </a>
                            </span>
                        <?php } ?>
                    </div>


                    <div class="span6" style="width:100%; margin:0 auto;">
                        <?php if($this->arrayFinalView['eightPhoto'][0][5] != NULL){ ?>
                            <span class="bandProfile1" style="float:left; margin:0 5px 0 55px;width:201px;">
                                <a data-height="<?php echo $this->arrayFinalView['eightPhoto'][0][5]['height']; ?>" data-width="<?php echo $this->arrayFinalView['eightPhoto'][0][5]['width']; ?>" href="<?php print APPLICATION_BASEURL .'/public/uploaded_resource/frontend/member/profile-image/'.$this->arrayFinalView['eightPhoto'][0][5]['vImg'] ?>" data-dateCreate="<?php echo $this->arrayFinalView['eightPhoto'][0][5]['dDate_create']; ?>" data-desc="<?php echo $this->arrayFinalView['eightPhoto'][0][5]['tDesc']; ?>" data-img="<?php echo $this->arrayFinalView['eightPhoto'][0][5]['vImg']; ?>">
                                    <img width="201px" height="165px" src="<?php print APPLICATION_BASEURL .'/public/uploaded_resource/frontend/member/profile-image/'.$this->arrayFinalView['eightPhoto'][0][5]['vImg'] ?>" alt="video" class="imgvid" style="margin:0;"/>
                                </a>
                            </span>
                        <?php }if($this->arrayFinalView['eightPhoto'][0][6] != NULL){ ?>
                            <span class="bandProfile1" style="float:left;margin:0 5px 0 5px;width:201px;">
                                <a data-height="<?php echo $this->arrayFinalView['eightPhoto'][0][6]['height']; ?>" data-width="<?php echo $this->arrayFinalView['eightPhoto'][0][6]['width']; ?>" href="<?php print APPLICATION_BASEURL .'/public/uploaded_resource/frontend/member/profile-image/'.$this->arrayFinalView['eightPhoto'][0][6]['vImg'] ?>" data-dateCreate="<?php echo $this->arrayFinalView['eightPhoto'][0][6]['dDate_create']; ?>" data-desc="<?php echo $this->arrayFinalView['eightPhoto'][0][6]['tDesc']; ?>" data-img="<?php echo $this->arrayFinalView['eightPhoto'][0][6]['vImg']; ?>">
                                    <img width="201px" height="165px" src="<?php print APPLICATION_BASEURL .'/public/uploaded_resource/frontend/member/profile-image/'.$this->arrayFinalView['eightPhoto'][0][6]['vImg'] ?>" alt="video" class="imgvid" style="margin:0;" />
                                </a>
                            </span>
                        <?php }if($this->arrayFinalView['eightPhoto'][0][7] != NULL){ ?>
                            <span class="bandProfile1" style="float:left;margin:0 5px 0 5px;width:201px;">
                                <a data-height="<?php echo $this->arrayFinalView['eightPhoto'][0][7]['height']; ?>" data-width="<?php echo $this->arrayFinalView['eightPhoto'][0][7]['width']; ?>" href="<?php print APPLICATION_BASEURL .'/public/uploaded_resource/frontend/member/profile-image/'.$this->arrayFinalView['eightPhoto'][0][7]['vImg'] ?>" data-dateCreate="<?php echo $this->arrayFinalView['eightPhoto'][0][7]['dDate_create']; ?>" data-desc="<?php echo $this->arrayFinalView['eightPhoto'][0][7]['tDesc']; ?>" data-img="<?php echo $this->arrayFinalView['eightPhoto'][0][7]['vImg']; ?>">
                                    <img width="201px" height="165px" src="<?php print APPLICATION_BASEURL .'/public/uploaded_resource/frontend/member/profile-image/'.$this->arrayFinalView['eightPhoto'][0][7]['vImg'] ?>" alt="video" class="imgvid"  style="margin:0;"/>
                                </a>
                            </span>
                        <?php }if($this->arrayFinalView['eightPhoto'][0][8] != NULL){ ?>
                            <span class="bandProfile1" style="float:left;margin:0 5px 0 5px;width:201px;">
                                <a data-height="<?php echo $this->arrayFinalView['eightPhoto'][0][8]['height']; ?>" data-width="<?php echo $this->arrayFinalView['eightPhoto'][0][8]['width']; ?>" href="<?php print APPLICATION_BASEURL .'/public/uploaded_resource/frontend/member/profile-image/'.$this->arrayFinalView['eightPhoto'][0][8]['vImg'] ?>" data-dateCreate="<?php echo $this->arrayFinalView['eightPhoto'][0][8]['dDate_create']; ?>" data-desc="<?php echo $this->arrayFinalView['eightPhoto'][0][8]['tDesc']; ?>" data-img="<?php echo $this->arrayFinalView['eightPhoto'][0][8]['vImg']; ?>">
                                    <img width="201px" height="165px" src="<?php print APPLICATION_BASEURL .'/public/uploaded_resource/frontend/member/profile-image/'.$this->arrayFinalView['eightPhoto'][0][8]['vImg'] ?>" alt="video" class="imgvid" style="margin:0;" />
                                </a>
                            </span>
                        <?php }if($this->arrayFinalView['eightPhoto'][0][9] != NULL){ ?>
                            <span class="bandProfile1" style="float:left;margin:0 5px 0 5px;width:201px;">
                                <a data-height="<?php echo $this->arrayFinalView['eightPhoto'][0][9]['height']; ?>" data-width="<?php echo $this->arrayFinalView['eightPhoto'][0][9]['width']; ?>" href="<?php print APPLICATION_BASEURL .'/public/uploaded_resource/frontend/member/profile-image/'.$this->arrayFinalView['eightPhoto'][0][9]['vImg'] ?>" data-dateCreate="<?php echo $this->arrayFinalView['eightPhoto'][0][9]['dDate_create']; ?>" data-desc="<?php echo $this->arrayFinalView['eightPhoto'][0][9]['tDesc']; ?>" data-img="<?php echo $this->arrayFinalView['eightPhoto'][0][9]['vImg']; ?>">
                                    <img width="201px" height="165px" src="<?php print APPLICATION_BASEURL .'/public/uploaded_resource/frontend/member/profile-image/'.$this->arrayFinalView['eightPhoto'][0][9]['vImg'] ?>" alt="video" class="imgvid" style="margin:0;" />
                                </a>
                            </span>
                        <?php } ?>
                    </div>
              

			
		</div><!-- /.row -->
		<?php if($this->arrayFinalView['eightPhoto'][1]>10){ ?>
		<div class="viewall"><a href="<?php echo APPLICATION_BASEURL.'/images/index/id/'.$this->arrayFinalView['member_id']; ?>" class="">VIEW ALL PHOTOS</a></div>
                <?php } ?>
	</div><!-- /.row -->
  </div><!-- /.container -->
  <?php } ?>
</div><!-- /#votingContent -->



<div id="modal_zoom_id" class="modalNew hide fade" tabindex="1" role="dialog" aria-labelledby="modal_header_id" aria-hidden="true">
    <div id="modal_body_id" class="modal-body">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
<!--        <div id="div_body_modal_id">-->
            <img class="img-rounded" />
<!--        </div>-->
        
    </div>
    
    <div class="modal-footer footerModal text-left">
        <div id="modal_footer_id" class="text-left">
            <h6 style="color: #2d5097;"></h6>
            <p></p>
        </div>
    </div>
</div>


<!--<div id="modal_zoom_id" class="modal hide fade" tabindex="1" role="dialog" aria-labelledby="modal_header_id" aria-hidden="true">
    <div id="modal_body_id" class="modal-body">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <div id="div_body_modal_id">
            <img style="min-width: 450px; min-height: 450px;" class="img-rounded" />
        </div>
        
    </div>
    
    <div class="modal-footer footerModal text-left">
        <div id="modal_footer_id" class="text-left">
            <h6 style="color: #2d5097;"></h6>
            <p></p>
        </div>
    </div>
</div>-->



    
