<div class="row-fluid">
    <input type="file" name="file_upload" id="file_upload" />
</div>


<div class="container-fluid">
    <div id="view_body_id" class="row-fluid">
        <ul id="ul_view_pic_id" class="thumbnails">
            
        </ul>
    </div>
</div>


<div id="modal_pic_id" class="modal hide fade" tabindex="1" role="dialog" aria-labelledby="modal_header_id" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <ul class="unstyled inline" style="display:inline">
            <li>
                <img id="pic_header_id" style="height: 100px; width: 100px;" />
            </li>
            <li>    
                <h5 id="title_band_id" style="color: #2d5097;"></h5>
<!--                <h6 id="date_create_id" style="color: #aaaaaa;"></h6>-->
            </li>
        </ul>
    </div>
    
    <div id="modal_body_id" class="modal-body">
        <div class="row-fluid">
            <div class="span7">
                <img class="img-rounded" id="img_body_id" />
            </div>
            <div class="span5">
                <div class="row-fluid">
                    <button class="btn btn-info span10" id="btn_set_pic_id" onclick="setAsProfile()"> set as profile pic </button>
                </div>
                <br />
                <div class="row-fluid footerModal">
                    <div class="text-left" id="footer_desc_id">
                        <div class="edit_area">
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
        
        
        
        
        
        
        
        
<!--        <div class="span8">
            <img class="img-rounded" id="img_body_id" />
            
        </div>
        <button class="btn btn-info span4" id="btn_set_pic_id" onclick="setAsProfile()"> set as profile pic </button>
        <div class="text-left" id="footer_desc_id">
            <div class="edit_area">
            </div>
        </div>-->
    </div>
    <span id="date_create_edti_id" style="margin-left: 10px; color: #707070;"></span>
    
<!--    <div class="modal-footer footerModal">
        
    </div>-->
</div>
