<div class="darkyellow-login" style="background:#de4a3c; width:100%; height:130px; margin:0 auto; padding:0; border-bottom:20px solid #b8382b;">
<p class="loginfbt">Videos</p>
<p class="loginfb">Music Videos and other Videos</p>
</div>


<div class="well" id="form-insert-movie" style="margin:0; display: none;padding: 40px">
    <div class="videoform" style=" height:auto; min-height:130px; margin:0 auto; padding:0; width:1070px;">
        <form id="form-movie-embed" data-type="status" style="margin:0;"  >
            <div class="leftform">
            <input type="text" placeholder="Title" value="" id="vVideo_title"  name="vVideo_title" class="titlebox" />
            <textarea placeholder="Description" class="textdescri" id="tDesc" name="tDesc"></textarea>
            </div>
            <div class="rightform">
                <input type="hidden" id="movie-iId-edit" value=""/>
                <textarea placeholder="Embed Code" class="embed_code" id="tVideo_embed_code" name="tVideo_embed_code"></textarea>
                <input class="submitvideo" value="Save Video" id="more-info-form-save" onclick="save_video()" style="text-align: center;cursor: pointer"/>
            </div>
        </form>
    </div>
</div>  <!--end of videoform-->


<div id="signupContent" style="min-height:350px; height:auto; margin:0 auto;">
    <div class="container" style="width:100%; margin:0 auto; background:#b8382b;">
        <div style="margin:0 auto; width:1250px;">

            <div style="float:left; height:auto; min-height:400px;width:637px; ">
                <div class="watchvideo">
                    <div id="movie-show-div-id">

                    </div>
                </div>  <!--end of watchvideo-->


                <div class="videodescription">
                    <p style="float:left; font-size:16px; margin:5px 0 0 5px;" id="movie-show-title-id">Name Here</p>
                    <div class="clear"></div>
                    <p style="float:left; font-size:16px; margin:5px 0 0 5px;height: auto" id="movie-show-desc-id"></p>
                </div>
            </div>

            <div class="loginform1" style="float:left; width:578px; height:auto; min-height:400px; margin:20px 0 0 20px;">
                <input type="button" id="botton-add-movie" class="addvideo" value="Add Video" />
                
                <div id="thumbnail-show-image-youtube" >
                </div>

            </div>        
        </div>     
    </div>
</div>


<!-- Modal delete movie-->
<div id="delete-movie-alert" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
<div class="modal-header">
<!--<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>-->
<h3 id="myModalLabel">Warning</h3>
</div>
<div class="modal-body">
<p>Are you sure you want to delete this video?</p>
</div>
<div class="modal-footer">
<button class="btn" data-dismiss="modal" aria-hidden="true">No</button>
<button class="btn btn-primary" id="yes-delete-move-id" onclick="">Yes</button>
</div>
</div>
