<!--<div id="modal_id" class="modal hide fade" tabindex="1" role="dialog" aria-labelledby="modal_header_id" aria_hidden="true">
    <div class="modal-header">
        <h6>
            ADD NEW MEMBER
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        </h6>
    </div>
    
    <div class="modal-body">
        
    </div>
</div>-->
<!--href="#modal_pic_id" data-toggle="modal"-->
<script>$.fn.editable.defaults.mode = 'inline';</script>
<div class="container-fluid">
    <div class="row-fluid">
        <div class="span12">
            <div class="row-fluid">
                <div class="span7 offset3">
                    <button id="btn_add_id" type="button" class="btn btn-primary span2">ADD</button>
                </div>
            </div>
            
            <div id="div_form_id" class="row-fluid" style="margin-top: 20px;" hidden="hidden">
                <div class="span7 offset3">
                    <form class="form-inline" method="post" action="<?php echo APPLICATION_BASEURL; ?>/bands-member/save-member" name="form-member" id="form_member_id">
                        <input type="text" name="name" placeholder="Name & Family" required/>
                        <input type="text" name="instrument" placeholder="Instrument" required/>
                        <button id="sub_btn_id" type="submit" class="btn" name="submit">submit</button>
                        <button type="reset" class="btn" value="reset" name="reset">close</button>
                    </form>
                </div>
            </div>
            
            <div class="row-fluid">
                <div class="span6 offset3">
                    <table class="table table-hover table-striped">
                        <thead hidden="hidden">
                            <tr>
                                <td><h6>Name & Family</h6></td>
                                <td><h6>Instrument</h6></td>
                                <td></td>
                            </tr>
                        </thead>
                        <tbody>
                            
                        </tbody>
                    </table>
                </div>
            </div>
            
<!--            <div class="row-fluid">
                <div id="pagination_id" class="span6 offset3">
                    
                </div>
            </div>-->
        </div>
    </div>
</div>
