<div class="span2"></div>
<div class="span8">
        <a  id="search-data-btn" href="#myModal" role="button" class="btn btn-inverse pull-right" data-toggle="modal">SEARCH</a>
        
        <button class="btn btn-primary pull-right" id="reset_search_data" data-search="" style="display: none">RESET SEARCH</button>
 
        <!-- Modal -->
        <div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h5 id="myModalLabel">Search Fan Name</h5>
            </div>
            <div class="modal-body">
                <form id="form-send-data" action="<?php echo APPLICATION_BASEURL; ?>/backend/fans">
                    <input type="text" name="search-data-name" id="search-data-name" placeholder="Name..."  style="width: 70%">
                    <input type="text" name="search-data-lastname" id="search-data-lastname" placeholder="Lastname..."  style="width: 70%">
                    <input type="text" name="search-data-email" id="search-data-email" placeholder="Email..."  style="width: 70%">
                    <input type="button" value="search" name="search-fan-name" id="search-fan-name" class="btn btn-success" style="margin-top:-10px; width: 25%" />
                </form>
            </div>
        </div>
    
            
        <table class="table table-striped">
            <thead id ="tHead_table_td">
            </thead>
            <tbody id ="tBody_table_td">
             
                
                
            </tbody>
        </table>
         <div class="row">
         <div  style="margin: auto;text-align: center">
             <div class="pagination">
                <ul id="ul-pagination-id">
                </ul>
            </div>
         </div>
     </div>
    
</div>
<div class="span2"></div>






<div id="editFan" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h5 id="title-fan-edit"></h5>
    </div>
    <div class="modal-body">
        <div class="span12" id="alert-login-faild"></div>
        <ul class="nav nav-tabs" id="editFanTab">
            <li class="active"><a href="#basicInfo">Basic Info</a></li>
            <li><a href="#othreInfo">Other Info</a></li>
        </ul>

        <div class="tab-content">
            <div class="tab-pane active" id="basicInfo">
                <form id="form-fan-edit-id" action="<?php echo APPLICATION_BASEURL; ?>/backend/fans" style="margin:0;"  >
                        <div class="span6">
                            <label>Email</label>
                            <input type="text" id="pre_vEmail" data-tab1="data" name="vEmail" placeholder="Email..." style="width:93%;" >
                            <label>name title</label>
                            <select id="pre_vName_title" data-tab1="data" name="vName_title" style="width:93%;">
                                <option value="Ms">Ms</option>
                                <option value="Mrs">Mrs</option>
                                <option value="Mr">Mr</option>
                            </select>
                            <input class="btn" value="Close" data-close="close" id="more-info-form-close" style="text-align: center;cursor: pointer;width: 89%"/>
<!--                            <input class="submitvideo" value="Close" data-close="close" id="more-info-form-close" style="text-align: center;cursor: pointer;width: 450px !important"/>-->
                        </div>
                        <div class="span6">
                            <label>name</label>
                            <input type="text" id="pre_vName" data-tab1="data" name="vName" placeholder="Name..." style="width:93%;" >
                            <label>last name</label>
                            <input type="text" id="pre_vLastname" data-tab1="data" name="vLastname" placeholder="last name..." style="width:93%;" >
                            <input class="btn btn-success" value="Save Information" id="more-info-form-save" style="text-align: center;cursor: pointer;width: 89%"/>
<!--                            <input class="submitvideo" value="Save Information" id="more-info-form-save" style="text-align: center;cursor: pointer;width: 550px !important;margin-top: 40px"/>-->
                        </div>
                </form>
            </div>
            <div class="tab-pane" id="othreInfo">
                <form id="form-fan-edit-id-tab2" action="<?php echo APPLICATION_BASEURL; ?>/backend/fans" style="margin:0;"  >
                    <div class="span6">
                        <label>Company</label>
                                <input type="text" id="pre_vCompany" data-tab2="data" name="vCompany" placeholder="Company..." style="width:93%;"  >

                                <label>Country</label>
                                <input type="text" id="pre_vCountry" data-tab2="data" name="vCountry" placeholder="Country..." style="width:93%;" >
                                <label>State</label>
                                <input type="text" id="pre_vState" data-tab2="data" name="vState" placeholder="State..." style="width:93%;" >
                                <label>City</label>
                                <input type="text" id="pre_vCity" data-tab2="data" name="vCity" placeholder="City..." style="width:93%;" >
                                <span>
                                <label>Birth Date</label>
                                <select id="pre_birthMonth" name="pre_birthMonth" style="width:33%" data-tab2="data">
                                    <option label="January" value="01">January</option>
                                    <option label="February" value="02">February</option>
                                    <option label="March" value="03">March</option>
                                    <option label="April" value="04">April</option>
                                    <option label="May" value="05">May</option>
                                    <option label="June" value="06">June</option>
                                    <option label="July" value="07">July</option>
                                    <option label="August" value="08">August</option>
                                    <option label="September" value="09">September</option>
                                    <option label="October" value="10">October</option>
                                    <option label="November" value="11">November</option>
                                    <option label="December" value="12">December</option>
                                </select>
                                <select id="pre_birthDay" name="pre_birthDay" style="width: 30%" data-tab2="data">
                                    <option value="1">1</option>
                                    <option value="2">2</option>
                                    <option value="3">3</option>
                                    <option value="4">4</option>
                                    <option value="5">5</option>
                                    <option value="6">6</option>
                                    <option value="7">7</option>
                                    <option value="8">8</option>
                                    <option value="9">9</option>
                                    <option value="10">10</option>
                                    <option value="11">11</option>
                                    <option value="12">12</option>
                                    <option value="13">13</option>
                                    <option value="14">14</option>
                                    <option value="15">15</option>
                                    <option value="16">16</option>
                                    <option value="17">17</option>
                                    <option value="18">18</option>
                                    <option value="19">19</option>
                                    <option value="20">20</option>
                                    <option value="21">21</option>
                                    <option value="22">22</option>
                                    <option value="23">23</option>
                                    <option value="24">24</option>
                                    <option value="25">25</option>
                                    <option value="26">26</option>
                                    <option value="27">27</option>
                                    <option value="28">28</option>
                                    <option value="29">29</option>
                                    <option value="30">30</option>
                                    <option value="31">31</option>
                                </select>
                                <select id="pre_birthYear" name="pre_birthYear" style="width: 30%" data-tab2="data">
                                    <!--<option label="2010" value="2010">2010</option>
                                    <option label="2009" value="2009">2009</option>
                                    <option label="2008" value="2008">2008</option>
                                    <option label="2007" value="2007">2007</option>
                                    <option label="2006" value="2006">2006</option>
                                    <option label="2005" value="2005">2005</option>
                                    <option label="2004" value="2004">2004</option>
                                    <option label="2003" value="2003">2003</option>
                                    <option label="2002" value="2002">2002</option>-->
                                    <option label="2001" value="2001">2001</option>
                                    <option label="2000" value="2000">2000</option>
                                    <option label="1999" value="1999">1999</option>
                                    <option label="1998" value="1998">1998</option>
                                    <option label="1997" value="1997">1997</option>
                                    <option label="1996" value="1996">1996</option>
                                    <option label="1995" value="1995">1995</option>
                                    <option label="1994" value="1994">1994</option>
                                    <option label="1993" value="1993">1993</option>
                                    <option label="1992" value="1992">1992</option>
                                    <option label="1991" value="1991">1991</option>
                                    <option label="1990" value="1990">1990</option>
                                    <option label="1989" value="1989">1989</option>
                                    <option label="1988" value="1988">1988</option>
                                    <option label="1987" value="1987">1987</option>
                                    <option label="1986" value="1986">1986</option>
                                    <option label="1985" value="1985">1985</option>
                                    <option label="1984" value="1984">1984</option>
                                    <option label="1983" value="1983">1983</option>
                                    <option label="1982" value="1982">1982</option>
                                    <option label="1981" value="1981">1981</option>
                                    <option label="1980" value="1980">1980</option>
                                    <option label="1979" value="1979">1979</option>
                                    <option label="1978" value="1978">1978</option>
                                    <option label="1977" value="1977">1977</option>
                                    <option label="1976" value="1976">1976</option>
                                    <option label="1975" value="1975">1975</option>
                                    <option label="1974" value="1974">1974</option>
                                    <option label="1973" value="1973">1973</option>
                                    <option label="1972" value="1972">1972</option>
                                    <option label="1971" value="1971">1971</option>
                                    <option label="1970" value="1970">1970</option>
                                    <option label="1969" value="1969">1969</option>
                                    <option label="1968" value="1968">1968</option>
                                    <option label="1967" value="1967">1967</option>
                                    <option label="1966" value="1966">1966</option>
                                    <option label="1965" value="1965">1965</option>
                                    <option label="1964" value="1964">1964</option>
                                    <option label="1963" value="1963">1963</option>
                                    <option label="1962" value="1962">1962</option>
                                    <option label="1961" value="1961">1961</option>
                                    <option label="1960" value="1960">1960</option>
                                    <option label="1959" value="1959">1959</option>
                                    <option label="1958" value="1958">1958</option>
                                    <option label="1957" value="1957">1957</option>
                                    <option label="1956" value="1956">1956</option>
                                    <option label="1955" value="1955">1955</option>
                                    <option label="1954" value="1954">1954</option>
                                    <option label="1953" value="1953">1953</option>
                                    <option label="1952" value="1952">1952</option>
                                    <option label="1951" value="1951">1951</option>
                                    <option label="1950" value="1950">1950</option>
                                    <option label="1949" value="1949">1949</option>
                                    <option label="1948" value="1948">1948</option>
                                    <option label="1947" value="1947">1947</option>
                                    <option label="1946" value="1946">1946</option>
                                    <option label="1945" value="1945">1945</option>
                                    <option label="1944" value="1944">1944</option>
                                    <option label="1943" value="1943">1943</option>
                                    <option label="1942" value="1942">1942</option>
                                    <option label="1941" value="1941">1941</option>
                                    <option label="1940" value="1940">1940</option>
                                    <option label="1939" value="1939">1939</option>
                                    <option label="1938" value="1938">1938</option>
                                    <option label="1937" value="1937">1937</option>
                                    <option label="1936" value="1936">1936</option>
                                    <option label="1935" value="1935">1935</option>
                                    <option label="1934" value="1934">1934</option>
                                    <option label="1933" value="1933">1933</option>
                                    <option label="1932" value="1932">1932</option>
                                    <option label="1931" value="1931">1931</option>
                                    <option label="1930" value="1930">1930</option>
                                    <option label="1929" value="1929">1929</option>
                                    <option label="1928" value="1928">1928</option>
                                    <option label="1927" value="1927">1927</option>
                                    <option label="1926" value="1926">1926</option>
                                    <option label="1925" value="1925">1925</option>
                                    <option label="1924" value="1924">1924</option>
                                    <option label="1923" value="1923">1923</option>
                                    <option label="1922" value="1922">1922</option>
                                    <option label="1921" value="1921">1921</option>
                                    <option label="1920" value="1920">1920</option>
                                    <option label="1919" value="1919">1919</option>
                                    <option label="1918" value="1918">1918</option>
                                    <option label="1917" value="1917">1917</option>
                                    <option label="1916" value="1916">1916</option>
                                    <option label="1915" value="1915">1915</option>
                                    <option label="1914" value="1914">1914</option>
                                    <option label="1913" value="1913">1913</option>
                                    <option label="1912" value="1912">1912</option>
                                    <option label="1911" value="1911">1911</option>
                                    <option label="1910" value="1910">1910</option>
                                </select>                                                   
                            </span>
                                                            
                                                            
                            <input class="btn" data-close="close" value="Close" id="more-info-form-close-tab2" style="text-align: center;cursor: pointer;width: 89%"/>
<!--                            <input class="submitvideo" value="Close" data-close="close" id="more-info-form-close-tab2" style="text-align: center;cursor: pointer;width: 450px !important"/>-->
                       
                    </div>
                    <div class="span6">
                        <label>Address</label>
                        <input type="text" id="pre_vAddress" data-tab2="data" name="vAddress" placeholder="Address..." style="width:93%;" >
                        <label>Address2</label>
                        <input type="text" id="pre_vAddress2" data-tab2="data" name="vAddress2" placeholder="vAddress2..." style="width:93%;" >

                        <label>Zipcode</label>
                        <input type="text" id="pre_vZipcode" data-tab2="data" name="vZipcode" placeholder="Zipcode..." style="width:93%;" >
                        <label>Phone</label>
                        <input type="text" id="pre_vPhone" data-tab2="data" name="vPhone" placeholder="Phone..." style="width:93%;" >
                        <label>Fax</label>
                        <input type="text" id="pre_vFax" data-tab2="data" name="vFax" placeholder="Fax..." style="width:93%;" >
                        <input type="hidden" id="pre_iId" data-tab2="data" name="iId" />
<!--                            <input class="submitvideo" value="Save Information" id="more-info-form-save-tab2" style="text-align: center;cursor: pointer;width: 550px !important"/>-->
                        <input class="btn btn-success" value="Save Information" id="more-info-form-save-tab2" style="text-align: center;cursor: pointer;width: 89%"/>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>


<div id="deleteFanMember" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="deleteFanMemberLabel">Warning</h3>
    </div>
    <div class="modal-body">
    <p>Are you sure to delete this fan member?</p>
    </div>
    <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">No</button>
    <button class="btn btn-primary" id="delete-fan-member-yes">Yes</button>
    </div>
</div>





