<?php
echo '<?xml version="1.0" encoding="UTF-8" ?>';
echo $this->doctype();
?>
<html>
    <head>
        <script type="text/javascript">
            var $projectExecPath = '<?php echo APPLICATION_BASEURL; ?>';
            var $AppVarSID = '<?php echo $this->currentSessionId; ?>';
            var $secureAppVarSID = '<?php echo $this->currentSessionIdSecurity; ?>';
        </script>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <link rel="shortcut icon" href="<?php echo APPLICATION_BASEURL; ?>/public/skins/frontend/default/images/fav/favicon.ico" type="image/x-icon">
        <link rel="icon" href="<?php echo APPLICATION_BASEURL; ?>/public/skins/frontend/default/images/fav/favicon.ico" type="image/x-icon">
        <?php
        echo $this->headTitle();
        $this->loadSkin($this->frontendSkin, $this->currentPageDetails['currentPageFilename']);
        echo $this->headLink();
        echo $this->headScript();
        ?>
    </head>

    <body>


		        
<!--        <div class="container-fluid">-->
            <div class="row-fluid">
                <nav class="navbar navbar-inverse">
                    <div class="navbar-inner">
                        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </a>
                        <a href="<?php echo APPLICATION_BASEURL; ?>" class="brand">Uproar Festival Battle of the Bands</a>
                        <div class="nav-collapse">
                            <ul class="nav pull-right">
                                <li><a href="<?php echo APPLICATION_BASEURL; ?>/browse">BROWSE</a></li>
                                <li><a href="<?php echo APPLICATION_BASEURL; ?>/info">INFO</a></li>
                                <li><a href="<?php echo APPLICATION_BASEURL; ?>/help">HELP</a></li>
                                <li><a href="<?php echo APPLICATION_BASEURL; ?>/blog">BLOG</a></li>
                                <li><a href="<?php echo APPLICATION_BASEURL ?>/signup">SIGN UP</a></li>
                                <li class="dropdown">
                                    <a class="dropdown-toggle" data-toggle="dropdown" href="<?php echo APPLICATION_BASEURL; ?>/login">
                                        LOGIN
                                        <b class="caret"></b>
                                    </a>
                                    <form class="dropdown-menu"  method="POST" style="padding: 10px" action="<?php echo APPLICATION_BASEURL; ?>/authentication/login">
                                        <div class="row-fluid">
                                            <label class="optional">Email</label>
                                            <input type="text" name="txt-email" id="txt-email" value="">

                                            <label class="optional">Password</label>
                                            <input type="password" name="txt-password" id="txt-password" value="">
                                        </div>
                                        <div class="row-fluid">
                                            <div class="span4">
                                                <input type="submit" value="Signin" class="btn btn-success">
                                            </div>
                                            <div class="span8">
                                                    <input type="checkbox" name="remmber" value="remmber">&nbsp;Remember Me?<br>
                                            </div>
                                        </div>
                                        <div>
                                            <a href="">Forgot Password?</a>
                                        </div>
                                    </form>
                                </li>
                                
                            </ul>
                        </div>
                    </div>
                </nav>
            </div>
<!--        </div>-->
        <div class="container-fluid">
            <div class="row-fluid">
                <div class="span12">
                    <?php print $this->layout()->content; ?>
                </div>
            </div>
            
        </div>

	</body