<?php
echo '<?xml version="1.0" encoding="UTF-8" ?>';
echo $this->doctype();
?>
<html>
    <head>
        <script type="text/javascript">
            var $projectExecPath = '<?php echo APPLICATION_BASEURL; ?>';
            var $AppVarSID = '<?php echo $this->currentSessionId; ?>';
            var $secureAppVarSID = '<?php echo $this->currentSessionIdSecurity; ?>';
        </script>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <link rel="shortcut icon" href="<?php echo APPLICATION_BASEURL; ?>/public/skins/frontend/default/images/fav/favicon.ico" type="image/x-icon">
        <link rel="icon" href="<?php echo APPLICATION_BASEURL; ?>/public/skins/frontend/default/images/fav/favicon.ico" type="image/x-icon">
        <?php
        echo $this->headTitle();
        $this->loadSkin($this->frontendSkin, $this->currentPageDetails['currentPageFilename']);
        echo $this->headLink();
        echo $this->headScript();
        ?>
    </head>

    <body>


		        
<!--        <div class="container-fluid">-->
            <div class="row-fluid">
                <nav class="navbar navbar-inverse">
                    <div class="navbar-inner">
                        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </a>
                        <a href="<?php echo APPLICATION_BASEURL; ?>" class="brand">Uproar Festival Battle of the Bands</a>
                        <div class="nav-collapse">
                            <ul class="nav pull-right">
                                <li><a href="<?php if($this->loggedUser->eType == 'Band'){echo APPLICATION_BASEURL.'/profile/band';}elseif ($this->loggedUser->eType == 'Fan') {echo APPLICATION_BASEURL.'/profile/fan';} ?>">PROFILE</a></li>
                                <li><a href="<?php echo APPLICATION_BASEURL; ?>/movies">MOVIES</a></li>
                                <li><a href="<?php echo APPLICATION_BASEURL; ?>/browse">BROWSE</a></li>
                                <li><a href="<?php echo APPLICATION_BASEURL; ?>/info">INFO</a></li>
                                <li><a href="<?php echo APPLICATION_BASEURL; ?>/help">HELP</a></li>
                                <li><a href="<?php echo APPLICATION_BASEURL; ?>/blog">BLOG</a></li>
                                <li><a href="<?php echo APPLICATION_BASEURL ?>/signout">SIGN OUT</a></li>
                           
                                
                            </ul>
                        </div>
                    </div>
                </nav>
            </div>
<!--        </div>-->
        <div class="container-fluid">
            <div class="row-fluid">
                <div class="span12">
                    <?php print $this->layout()->content; ?>
                </div>
            </div>
            
        </div>

	</body